//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace go_property.co.za.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        public int Listing_Id { get; set; }
        public int Listing_Type_Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> Bedroom_Num { get; set; }
        public Nullable<int> Bathroom_Num { get; set; }
        public string Address_L1 { get; set; }
        public string Address_L2 { get; set; }
        public string Suburb { get; set; }
        public string Town_City { get; set; }
        public string Zip_Code { get; set; }
        public string Features { get; set; }
        public Nullable<decimal> Listing_Price { get; set; }
        public Nullable<int> Property_Type_Id { get; set; }
        public string Property_Name { get; set; }
    
        public virtual Listing_Type Listing_Type { get; set; }
    }
}
